### ISSUE TITLE
submission must be accepted only after the payment is approved

### ISSUE THREAD

**Issue by ngrhd** [razorpay/razorpay-gravity-forms#12]
Once 'submit' button is clicked, forms gets submitted successfully even before the payment is approved.
It becomes a major headache when reconciliation with the actual payments received with the user information captured.
How can I prevent this issue?

**Comment by karthigeyan15** [comment]
I have same problem how to resolve it please tell me

**Comment by ImPrasadM** [comment]
I am facing same problem, please tell us, We are facing serious issue.

**Comment by isaumya** [comment]
Please check this reply: https://github.com/razorpay/razorpay-gravity-forms/issues/15#issuecomment-503525415

**Comment by prem-techchefs** [comment]
Added feature in latest version. You can select option to getting email notification after payment or before payment.

**Comment by advaitn** [comment]
> Please check this reply: [#15 (comment)](https://github.com/razorpay/razorpay-gravity-forms/issues/15#issuecomment-503525415)
> Added feature in latest version. You can select option to getting email notification after payment or before payment.

But can entries be prevented if the payment is anything except success? Like if somebody purposely cancels the payment the entry is still made, notifications is fine, but I don't want that entry to be passed into the database. Is it possible via the update?

**Comment by isaumya** [comment]
@advaitn Please note that by default gravity form will add entries as soon as a form is submitted even before handling the payment notification events. Thus, the Gravity Form keeps all entries regardless of whether the payment was successful or not. No payment plugin can modify this feature as this is a very niche feature that you may want but not others.

Others may want to see the unsuccessful payment cases so that they can manually contact them and try to convert them. Anyways the point is it is not something everyone will want. But if you want this feature you can easily have it by writing a few lines of code. Check: https://docs.gravityforms.com/delete-entry-data-after-submission/

You just have to check if the payment is successful before deleting it. Try writing the code, if you stuck somewhere you can always ask at StackOverflow. In short, what you are looking for is out of the scope of this plugins.

### ⚠️ Important Note About Razorpay WordPress Dev Team

- After today, don't bother posting any bugs or issues or your problem here at GitHub or in WordPress support forum as the Razorpay team pay no head to them. I've personally passed the pathetic situation and sub-par code quality of the Razorpay WP dev team to many senior officials and even to Harshil directly and always your reaction in front of me is like yeah we are looking into it but as soon as I turn they are like meh!

- Personally I feel there is no competent dedicated WordPress integration team at Razorpay and it's like some guys are working on these lost causes in their free time, making some minor changes once a year rather than looking at the community, taking feedback and constantly improving it. That is not their goal or intension. You might have seen that there are multiple support threads in the WordPress plugin support section and Razorpay WP Dev team don't even bother looking at them or replying them. Same with reviews and GitHub issues.

- If you open a GitHub issue inside a Razorpay WP plugin repo, first of all, don't expect any reply for months and after many months you might gen like a one-liner reply after reading which you will feel like the dev team don't want to interact with you and they will immediately close your issue. Sometimes, your issue might get closed even without a reply.

- When I developed [Razorpay Gravity Forms - Updated](https://github.com/isaumya/razorpay-gravity-forms-updated) after being completely frustrated by the sheer patheticness of the official plugin by the Razorpay Dev team, I shared it publicly as an open-source project so that the Razorpay Dev team can look into it, team it and improve upon the improvements I've made on the updated plugin. Both in terms of feature (like adding the payment status based email notification support) as well as UI (lots of improvements on the disgusting UI of this Official Razorpay Gravity Forms plugin).

- Now after months of this when the Razorpay Dev team pushed an update to their plugin they just somehow added the payment status based email notification feature while keeping the UI similarly pathetic and published it to the world for production website use. Simply unbelievable.

- When when I looked at the source code on this official Razorpay Gravity Forms plugin, it was super clear that this was basically a copy/paste of the Stripe for Gravity Forms plugins and then updating the code on top of that. The Team didn't even wrote the code from scratch. 

Despite so many issues and Razorpay dev team having no interest on the WordPress integration, don't expect any quality improvement, support or anything. Even when you inform about the same to the Co-founder of a company and still nothing changes, you really can't do anything about it.

**Comment by advaitn** [comment]
> @advaitn Please note that by default gravity form will add entries as soon as a form is submitted even before handling the payment notification events. Thus, the Gravity Form keeps all entries regardless of whether the payment was successful or not. No payment plugin can modify this feature as this is a very niche feature that you may want but not others.
> 
> Others may want to see the unsuccessful payment cases so that they can manually contact them and try to convert them. Anyways the point is it is not something everyone will want. But if you want this feature you can easily have it by writing a few lines of code. Check: https://docs.gravityforms.com/delete-entry-data-after-submission/
> 
> You just have to check if the payment is successful before deleting it. Try writing the code, if you stuck somewhere you can always ask at StackOverflow. In short, what you are looking for is out of the scope of this plugins.
> 
> ### ⚠️ Important Note About Razorpay WordPress Dev Team
> * After today, don't bother posting any bugs or issues or your problem here at GitHub or in WordPress support forum as the Razorpay team pay no head to them. I've personally passed the pathetic situation and sub-par code quality of the Razorpay WP dev team to many senior officials and even to Harshil directly and always your reaction in front of me is like yeah we are looking into it but as soon as I turn they are like meh!
> * Personally I feel there is no competent dedicated WordPress integration team at Razorpay and it's like some guys are working on these lost causes in their free time, making some minor changes once a year rather than looking at the community, taking feedback and constantly improving it. That is not their goal or intension. You might have seen that there are multiple support threads in the WordPress plugin support section and Razorpay WP Dev team don't even bother looking at them or replying them. Same with reviews and GitHub issues.
> * If you open a GitHub issue inside a Razorpay WP plugin repo, first of all, don't expect any reply for months and after many months you might gen like a one-liner reply after reading which you will feel like the dev team don't want to interact with you and they will immediately close your issue. Sometimes, your issue might get closed even without a reply.
> * When I developed [Razorpay Gravity Forms - Updated](https://github.com/isaumya/razorpay-gravity-forms-updated) after being completely frustrated by the sheer patheticness of the official plugin by the Razorpay Dev team, I shared it publicly as an open-source project so that the Razorpay Dev team can look into it, team it and improve upon the improvements I've made on the updated plugin. Both in terms of feature (like adding the payment status based email notification support) as well as UI (lots of improvements on the disgusting UI of this Official Razorpay Gravity Forms plugin).
> * Now after months of this when the Razorpay Dev team pushed an update to their plugin they just somehow added the payment status based email notification feature while keeping the UI similarly pathetic and published it to the world for production website use. Simply unbelievable.
> * When when I looked at the source code on this official Razorpay Gravity Forms plugin, it was super clear that this was basically a copy/paste of the Stripe for Gravity Forms plugins and then updating the code on top of that. The Team didn't even wrote the code from scratch.
> 
> Despite so many issues and Razorpay dev team having no interest on the WordPress integration, don't expect any quality improvement, support or anything. Even when you inform about the same to the Co-founder of a company and still nothing changes, you really can't do anything about it.

I agree, it's really pathetic, I myself had to make a lot of changes to make the callback page good looking.

I tried doing the Delete after Submission but in my functions.php I cannot use **$entry[''payment_status"]  = "Paid"**,  it throws out some error  after successful payment. Any leads?

**Comment by isaumya** [comment]
@advaitn now your question comes to debugging territory. What I would do in your scenario is simply `var_dump` the `$entry['payment_status']` to see what value I'm getting in the first place before going with the conditional check.

Hope this helps. :)

**Comment by advaitn** [comment]
> @advaitn now your question comes to debugging territory. What I would do in your scenario is simply `var_dump` the `$entry['payment_status']` to see what value I'm getting in the first place before going with the conditional check.
> 
> Hope this helps. :)
> 
> On a side note, please for god sake stop using `==` it's 2020 now. Try `===` which is more consistent and typed as it will also compare the type along with the value.

The var_dump would return NULL since the form is already submitted, before the payment. Is there any payment hook that could help me?

**Comment by isaumya** [comment]
@advaitn YOu then can write a script and run it as a corn job. Each day search for all the entries with payment failed and delete them.
